//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projek.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TokobediaEntities : DbContext
    {
        public TokobediaEntities()
            : base("name=TokobediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetailTransaction> DetailTransactions { get; set; }
        public virtual DbSet<HeaderTransaction> HeaderTransactions { get; set; }
        public virtual DbSet<MsCart> MsCarts { get; set; }
        public virtual DbSet<MsPaymentType> MsPaymentTypes { get; set; }
        public virtual DbSet<MsProduct> MsProducts { get; set; }
        public virtual DbSet<MsProductType> MsProductTypes { get; set; }
        public virtual DbSet<MsRole> MsRoles { get; set; }
        public virtual DbSet<MsUser> MsUsers { get; set; }
    }
}
